apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wazuh-credentials
  namespace: soc-wazuh
  labels:
    app.kubernetes.io/managed-by: soc-gitops
    soc.lab/component: eso-external-secret
  annotations:
    soc.lab/vault-path: "credentials/wazuh-credentials"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: wazuh-credentials
    creationPolicy: Owner
  data:
    - secretKey: indexer_password
      remoteRef:
        key: credentials/wazuh-credentials
        property: indexer_password
    - secretKey: indexer_password_hash
      remoteRef:
        key: credentials/wazuh-credentials
        property: indexer_password_hash
    - secretKey: dashboard_password
      remoteRef:
        key: credentials/wazuh-credentials
        property: dashboard_password
    - secretKey: dashboard_password_hash
      remoteRef:
        key: credentials/wazuh-credentials
        property: dashboard_password_hash
