apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: thehive-sa-foundations
  namespace: soc-thehive
  labels:
    app.kubernetes.io/managed-by: soc-gitops
    soc.lab/component: eso-external-secret
  annotations:
    soc.lab/vault-path: "service-accounts/thehive-sa"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: thehive-sa-foundations
    creationPolicy: Owner
  data:
    - secretKey: api_key
      remoteRef:
        key: service-accounts/thehive-sa
        property: api_key
    - secretKey: login
      remoteRef:
        key: service-accounts/thehive-sa
        property: login
