apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cortex-postgresql-auth
  namespace: soc-cortex
  labels:
    app.kubernetes.io/managed-by: soc-gitops
    soc.lab/component: eso-external-secret
  annotations:
    soc.lab/vault-path: "databases/cortex-postgresql"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cortex-postgresql-auth
    creationPolicy: Owner
  data:
    - secretKey: postgres-password
      remoteRef:
        key: databases/cortex-postgresql
        property: postgres-password
    - secretKey: password
      remoteRef:
        key: databases/cortex-postgresql
        property: password
