apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: misp-app-secret
  namespace: soc-core
  labels:
    app.kubernetes.io/managed-by: soc-gitops
    soc.lab/component: eso-external-secret
  annotations:
    soc.lab/vault-path: "apps/misp-app-secret"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: misp-app-secret
    creationPolicy: Owner
  data:
    - secretKey: admin_email
      remoteRef:
        key: apps/misp-app-secret
        property: admin_email
    - secretKey: admin_password
      remoteRef:
        key: apps/misp-app-secret
        property: admin_password
    - secretKey: salt
      remoteRef:
        key: apps/misp-app-secret
        property: salt
    - secretKey: gpg_passphrase
      remoteRef:
        key: apps/misp-app-secret
        property: gpg_passphrase
