apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Placeholder — configuration Vault post-bootstrap à versionner ici
# (Policies, Auth Methods, SecretsEngines via vault-operator ou scripts)
resources: []
