## Exemple à intégrer à proxmox pour la création d'une VM Ubuntu 24.04 avec cloud-init

#cloud-config
package_update: true
packages:
  - qemu-guest-agent

ssh_pwauth: false

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: true
    # Les clés SSH seront injectées par Proxmox/OpenTofu (ne rien mettre ici)

growpart:
  mode: auto
  devices: ['/']

resize_rootfs: true

runcmd:
  - systemctl enable --now qemu-guest-agent
  - sed -i '/ swap / s/^/#/' /etc/fstab || true
  - swapoff -a || true
  - sysctl -w net.ipv4.ip_forward=1