---
galaxy_info:
  role_name: thehive
  author: soc-admin
  description: "Déploie TheHive 5 (plateforme d'investigation) via Helm"
  company: SOC-as-code
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - "22.04"
        - "24.04"
  galaxy_tags:
    - kubernetes
    - soc
    - security

dependencies: []
