---
- name: Install python venv + pip (bastion)
  ansible.builtin.apt:
    name:
      - python3-pip
      - python3-venv
    state: present
    update_cache: true
  delegate_to: localhost
  run_once: true
  become: true

- name: Create venv for ansible k8s modules (bastion)
  ansible.builtin.command: python3 -m venv /opt/ansible-k8s-venv
  args:
    creates: /opt/ansible-k8s-venv/bin/python
  delegate_to: localhost
  run_once: true
  become: true

- name: Install kubernetes python client in venv (bastion)
  ansible.builtin.pip:
    name:
      - kubernetes>=26.1.0
      - PyYAML
      - requests
    virtualenv: /opt/ansible-k8s-venv
  delegate_to: localhost
  run_once: true
  become: true

- name: Add metallb repo (once)
  kubernetes.core.helm_repository:
    name: metallb
    repo_url: https://metallb.github.io/metallb
    binary_path: "{{ helm_binary_path }}"
  delegate_to: localhost
  run_once: true
  become: false

- name: Update helm repos (once)
  ansible.builtin.command: "{{ helm_binary_path }} repo update"
  delegate_to: localhost
  run_once: true
  become: false

- name: Install/upgrade metallb
  kubernetes.core.helm:
    name: metallb
    chart_ref: metallb/metallb
    chart_version: "{{ metallb_version }}"
    release_namespace: "{{ metallb_namespace }}"
    create_namespace: true
    kubeconfig: "{{ kubeconfig_path }}"
    wait: true
    timeout: "10m0s"
    binary_path: "{{ helm_binary_path }}"
  delegate_to: localhost
  run_once: true
  become: false

- name: Create IPAddressPool + L2Advertisement
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    definition:
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: "{{ metallb_pool_name }}"
        namespace: "{{ metallb_namespace }}"
      spec:
        addresses:
          - "{{ metallb_ip_range }}"
  delegate_to: localhost
  run_once: true
  become: false
  vars:
    ansible_python_interpreter: /opt/ansible-k8s-venv/bin/python

- name: Create L2Advertisement
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    definition:
      apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        name: l2adv
        namespace: "{{ metallb_namespace }}"
      spec:
        ipAddressPools:
          - "{{ metallb_pool_name }}"
  delegate_to: localhost
  run_once: true
  become: false
  vars:
    ansible_python_interpreter: /opt/ansible-k8s-venv/bin/python
