---
soc_core_namespace: soc-core

bitnami_repo_name: bitnami
bitnami_repo_url: https://charts.bitnami.com/bitnami

misp_db_release: misp-mariadb
mariadb_chart_ref: bitnami/mariadb
mariadb_chart_version: "20.5.3"   # exemple, pinne ta version

misp_redis_release: misp-redis
redis_chart_ref: bitnami/redis
redis_chart_version: "20.6.2"     # exemple, pinne ta version

# Services internes (DNS k8s)
misp_db_host: "{{ misp_db_release }}-mariadb.{{ soc_core_namespace }}.svc.cluster.local"
misp_db_name: misp
misp_db_user: misp

misp_redis_host: "{{ misp_redis_release }}-master.{{ soc_core_namespace }}.svc.cluster.local"

# Exposition
misp_fqdn: misp.apps.soc.lab

# Compte admin
misp_admin_email: admin@soc.lab

# Image MISP (mets celle que tu utilises réellement)
# -> tu peux la remplacer par ton image validée/packagée en interne.
misp_image: "arintriyanto/misp-docker:latest"
