---
galaxy_info:
  role_name: soc_automation
  author: soc-admin
  description: "Configure l'automatisation SOC : credentials, webhooks Wazuh, mappings Cortex"
  company: SOC-as-code
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - "22.04"
        - "24.04"
  galaxy_tags:
    - kubernetes
    - soc
    - security

dependencies: []
