---
galaxy_info:
  role_name: databases
  author: soc-admin
  description: "Déploie les bases PostgreSQL partagées via Helm (Bitnami)"
  company: SOC-as-code
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - "22.04"
        - "24.04"
  galaxy_tags:
    - kubernetes
    - soc
    - security

dependencies: []
