---
- name: Deploy Wazuh (Indexer + Manager + Dashboard) via Helm
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    ansible_python_interpreter: "{{ k8s_ansible_python | default('python3') }}"

  roles:
    - role: wazuh
