---
galaxy_info:
  role_name: os_prereqs
  author: soc-admin
  description: "Configure le système d'exploitation (swap, sysctl, modules kernel)"
  company: SOC-as-code
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - "22.04"
        - "24.04"
  galaxy_tags:
    - kubernetes
    - soc
    - security

dependencies: []
