helm_binary_path: "helm"

soc_core_namespace: "soc-core"

bitnami_repo_name: "bitnami"
bitnami_repo_url: "https://charts.bitnami.com/bitnami"

# Releases names
thehive_pg_release: "thehive-postgresql"
cortex_pg_release: "cortex-postgresql"
misp_db_release: "misp-mariadb"

# Chart refs
postgres_chart_ref: "bitnami/postgresql"
mariadb_chart_ref: "bitnami/mariadb"

# Versions (pin = bonne pratique)
postgres_chart_version: "15.5.38"
mariadb_chart_version: "24.0.3"


k8s_ansible_venv: /opt/ansible-k8s-venv
k8s_ansible_python: "{{ k8s_ansible_venv }}/bin/python"