---
# --- Versions & cluster ---
cluster_name: soc-k8s
kubernetes_version: "v1.30.4"        # version pinning kubeadm/kubelet/kubectl
cri: containerd
kubelet_cgroup_driver: systemd
kubeadm_api_version: "kubeadm.k8s.io/v1beta3"
helm_binary_path: /usr/local/bin/helm
kubeconfig_path: /home/mgmt-user/SOC-as-code/ansible/playbooks/artifacts/admin.conf

# --- Réseaux Kubernetes ---
pod_cidr: "10.244.0.0/16"            # Calico par défaut
service_cidr: "10.96.0.0/12"

# --- Containerd (socket kubeadm) ---
cri_socket: "unix:///run/containerd/containerd.sock"

# --- CNI (choix) ---
cni: cilium

# Cilium - MVP
cilium_version: "1.15.6"         # par ex.
cilium_kubeproxy_replacement: "disabled"  # MVP : on garde kube-proxy
cilium_routing_mode: "tunnel"    # simple (VXLAN). Plus tard: "native"
cilium_hubble_enabled: true
cilium_hubble_ui: true
cilium_prometheus_enabled: true   # métriques agent + operator

# --- DNS du cluster ---
cluster_dns: "10.96.0.10"            # IP kube-dns dans le service CIDR
cluster_domain: "cluster.local"

# MetalLB
metallb_namespace: metallb-system
metallb_version: "0.14.9"          # exemple stable
metallb_pool_name: default-pool
metallb_ip_range: "10.0.30.50-10.0.30.80"   # adapte à TON réseau L2

# BGP
metallb_my_asn: 65010          # ASN MetalLB (speakers)
metallb_router_asn: 65000      # ASN OPNsense/FRR
metallb_router_ip: "10.0.20.254"

# Optionnel (souvent utile)
metallb_bgp_peer_name: "opnsense"
metallb_bgp_adv_name: "bgp-adv"
metallb_peer_port: 179
metallb_hold_time: "180s"
metallb_keepalive_time: "60s"
metallb_communities: []        # ex: ["65000:100"]

# Ingress NGINX
ingress_nginx_namespace: ingress-nginx
ingress_nginx_chart_version: "4.11.3"       # exemple stable

# --- Bastion (pour copier le kubeconfig si tu veux) ---
bastion_copy_kubeconfig: true
bastion_user: "mgmt-user"
bastion_host: "10.0.10.10"           # mgmt-soc
