---
galaxy_info:
  role_name: kubeadm_control_plane
  author: soc-admin
  description: "Initialise le control-plane Kubernetes avec kubeadm"
  company: SOC-as-code
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - "22.04"
        - "24.04"
  galaxy_tags:
    - kubernetes
    - soc
    - security

dependencies: []
