apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# CRs MetalLB — IPAddressPool, BGPPeer, BGPAdvertisement
# Appliqués dans le même Application ArgoCD que le chart Helm (multi-source)
resources:
  - ip-address-pool.yaml
  - bgp-peer.yaml
  - bgp-advertisement.yaml
