---
galaxy_info:
  role_name: wazuh
  author: soc-admin
  description: "Déploie Wazuh (SIEM/EDR) via Helm avec indexer, manager et dashboard"
  company: SOC-as-code
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - "22.04"
        - "24.04"
  galaxy_tags:
    - kubernetes
    - soc
    - security

dependencies: []
