name: Validate IaC
on: [push, pull_request]
jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: iac
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.6.0

      - name: Init (download providers)
        run: tofu init -input=false

      - name: Validate
        run: tofu validate -no-color